# Generated by Django 3.1.7 on 2022-09-27 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'Vegetarian'), ('2', 'Non-Vegetarian')], max_length=5)),
                ('desc', models.TextField(default='')),
                ('ingredients', jsonfield.fields.JSONField(default=dict)),
                ('steps', jsonfield.fields.JSONField(default=dict)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('pub_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='media/')),
                ('recipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.recipe')),
            ],
        ),
    ]
